name: Nightly Agent Runner

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: web
        run: npm ci
      - name: Run nightly agent
        working-directory: web
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AGENT_BASE_URL: ${{ vars.AGENT_BASE_URL }}
        run: |
          node scripts/nightly_agent.mjs > nightly-agent.log 2>&1
      - name: Upload agent log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nightly-agent-log
          path: web/nightly-agent.log
