name: Repair Bot

on:
  workflow_run:
    workflows: ["E2E", "Nightly Agent Runner"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read
  checks: read

jobs:
  analyze-and-suggest:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd web || true
          if [ -f package.json ]; then npm ci || npm i; fi

      - name: Run repair bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || '' }}
          RUN_ID: ${{ github.event.workflow_run.id }}
          REPO: ${{ github.repository }}
        run: node web/scripts/repair-bot.mjs
